    - name: Install Android SDK and Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools

        # Baixar e configurar o Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest

        # Aceitar licenças e instalar componentes necessários
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # Copiar o SDK completo para o local esperado pelo Buildozer
        mkdir -p /home/runner/.buildozer/android/platform/
        cp -r $ANDROID_SDK_ROOT /home/runner/.buildozer/android/platform/android-sdk

        # Garantir que 'aidl' seja executável
        chmod +x /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.2/aidl

        # Voltar para o projeto e rodar o build
        cd $GITHUB_WORKSPACE
        buildozer android debug
